 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: priya-flask-node-deployment
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: flasknode
   template:
     metadata:
       labels:
         app: flasknode
     spec:
       containers:
       - name: flasknode
         image: icr.io/priya_expense_tracker2/flask-template2
         imagePullPolicy: Always
         ports:
         - containerPort: 5000
